task: backflip
state_dim: ???
action_dim: ???
device: cuda
seed: 0
wandb: true

# whether to train model or train policy
train_dynamics: true

# data
level: medium

# everything about dynamics model training
dynamics_training:
  state_dim: ${state_dim}
  action_dim: ${action_dim}
  hidden_dims: [2048, 2048, 2048, 2048]

  single_step: true
  model_type: reg
  normalize_inputs: true
  n_models: 5
  activation: relu
  seed: ${seed}
  device: ${device}

  optim: adam
  n_epochs: 1000
  batch_size: 256
  lr: 3e-4
  grad_clip: 0.0
  train_for_diff: true

  discrepancy:
    max_diff: true

  