state_dim: ???
action_dim: ???
device: cuda
seed: 0
wandb: true

# whether to train model or train policy
train_dynamics: true

# all data config params (expert + offline)
data:
  expert:
    n_samples: 50000

  offline:
    n_samples: 100000

# everything about dynamics model training
dynamics_training:
  state_dim: ${state_dim}
  action_dim: ${action_dim}
  hidden_dims: [512, 512, 512, 512]

  normalize_inputs: true
  n_models: 5
  seed: ${seed}
  device: ${device}

  n_epochs: 1000
  batch_size: 256
  lr: 3e-4
  grad_clip: 0.0
  train_for_diff: true

  discrepancy:
    max_diff: false

  